### ISSUE TITLE
Plot functions handle color selection differently

### ISSUE THREAD

**Issue by chroetz** [pik-piam/mip#25]
`mipArea()` uses `plotstyle(as.character(unique(x[[dimToStack]])))`, `mipBarYearData()` uses `plotstyle(levels(x$variable))` to obtain colors for plotted objects. This may lead to inconsistent assignment of colors, in particular when `x$variable` and `x[[dimToStack]]` are factors with levels not in `plotstyle.csv`: Compare `plotstyle(levels(factor(3:1)))` and `plotstyle(as.character(unique(factor(3:1))))`.

**Comment by dklein-pik** [comment]
I am confused. Isn't the check you suggest above supposed to deliver different results? I get the same colors:
```
> plotstyle(levels(factor(3:1)))
        1         2         3 
"#E41A1C" "#377EB8" "#4DAF4A" 
> plotstyle(as.character(unique(factor(3:1))))
        3         2         1 
"#E41A1C" "#377EB8" "#4DAF4A" 
```

**Comment by chroetz** [comment]
The colors are the same but how they are matched to the names of the levels is different. The order is 1 2 3 in your frist result and 3 2 1 in the second
