### ISSUE TITLE
Extend Y-Scales to Zero?

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mip#28]
> - The all new functions with a `scales` argument have `"free_y"` as a default. 

— [pik-piam/remind2/#182](https://github.com/pik-piam/remind2/pull/182)

Maybe it is worthwhile to extend y-axes to zero by default, or at least give the option to do so (using `ggplot2::expand_limits()`.  It makes judging relative changes easier.  @robertpietzcker might have feelings on this topic, too.

**Comment by robertpietzcker** [comment]
Yes, I do have strong feelings! :-)
Thanks for making this connection, Michaja!

@chroetz We had discussed in a REMIND meeting sometime last year that we want the default setting to be that all plots always go down to zero, for the reason Michaja gave: when they all go to 0, it is much easier to quickly scan a large number of plots and identify which ones need specific attention, compared to a situation where the scale only depends on whether the plotted data is flat vs increasing/decreasing (and in the first case zooming in).

**Comment by chroetz** [comment]
That makes sense! I will implement the necessary changes

**Comment by chroetz** [comment]
I haven't seen any plots that do not start at 0. But I use `ylim(0, NA)` which I will change to `expand_limits(y = 0)` as suggested by @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
`ylim(0, NA)` and  `expand_limits(y = 0)` are functionally identical (I think).
This was triggered by the `scales = 'free_y'` default, which would have cause strange axes, hadn't you reigned that in already.  50 DKP for you!
