### ISSUE TITLE
plotstyle() colours for PE (possibly others)

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mip#9]
I find the colours `plotstyle()` returns for PE carriers … odd.
```R
mip::plotstyle(c('PE|Coal', 
                 'PE|Oil', 
                 'PE|Gas', 
                 'PE|Nuclear', 
                 'PE|Hydro', 
                 'PE|Biomass', 
                 'PE|Geothermal', 
                 'PE|Solar', 
                 'PE|Wind'),
               plot = TRUE)
```
![mip_plotstyles_PE](https://user-images.githubusercontent.com/53254462/71587980-1d600000-2b20-11ea-84c0-fd04a58d986f.png)
Wouldn't it be worthwhile to change that to something more easily associated with the energy carriers in question?  I think we were using different colours before.

**Comment by dklein-pik** [comment]
The reason is that there were no colors defined for "PE|*" but only for "Primary Energy|*". I added the corresponding entries to the plotstyle.csv

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I see.  Didn't `plotstyle()` return 50 shades of grey for unknown entries?  I guess that's why I assumed this would be defined colours.  Maybe it could give a `message()` informing the user that he got something made up.

**Comment by dklein-pik** [comment]
1. Maybe a bit hidden: you can get this message by setting verbosity to 1 (see help). 
2. At some point we replaced the shades of grey by colors (is this not useful?)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
>     2\. At some point we replaced the shades of grey by colors (is this not useful?)
Just unexpected.  The sea of grey was my personal 'undefined entries' indicator ;)
